package com.lvhao.dao;

import com.lvhao.entity.Account;
import com.lvhao.entity.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AccountMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  long countByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int deleteByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int insert(Account row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int insertSelective(Account row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  List<Account> selectByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  Account selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int updateByPrimaryKeySelective(Account row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * account
   *
   * @mbg.generated Wed Jul 19 10:35:16 CST 2023
   */
  int updateByPrimaryKey(Account row);
}
