package com.lvhao.dao;

import com.lvhao.entity.Balance;
import com.lvhao.entity.BalanceExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BalanceMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  long countByExample(BalanceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int deleteByExample(BalanceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int deleteByPrimaryKey(Integer userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int insert(Balance row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int insertSelective(Balance row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  List<Balance> selectByExample(BalanceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  Balance selectByPrimaryKey(Integer userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int updateByExampleSelective(@Param("row") Balance row, @Param("example") BalanceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int updateByExample(@Param("row") Balance row, @Param("example") BalanceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int updateByPrimaryKeySelective(Balance row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * balance
   *
   * @mbg.generated Sun Jul 16 18:48:36 CST 2023
   */
  int updateByPrimaryKey(Balance row);
}
