package com.lvhao.entity;

public class Balance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.user_id
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.user_name
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.balance
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.user_id
     *
     * @return the value of balance.user_id
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.user_id
     *
     * @param userId the value for balance.user_id
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.user_name
     *
     * @return the value of balance.user_name
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.user_name
     *
     * @param userName the value for balance.user_name
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column balance.balance
     *
     * @return the value of balance.balance
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column balance.balance
     *
     * @param balance the value for balance.balance
     *
     * @mbg.generated Sun Jul 16 18:48:36 CST 2023
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}