spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/spring_persistence?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
